<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>KioskClient.Core</RootNamespace>
    <AssemblyName>KioskClient.Core</AssemblyName>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Company>City of Stanton</Company>
    <Product>Kiosk Client</Product>
    <Copyright>Copyright (c) 2021-2026 City of Stanton. All rights reserved.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
