
name: Build and Test UWP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools with UWP workload
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.UWPBuildTools --includeRecommended --includeOptional --passive --norestart" --yes
          choco install vswhere --yes

      - name: Find MSBuild
        id: msbuild
        run: |
          msbuild_path=$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)
          echo "MSBUILD_PATH=$msbuild_path" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Build Solution (UWP)
        run: |
          & "$env:MSBUILD_PATH" KioskClient.sln /t:Restore /p:Configuration=Release
          & "$env:MSBUILD_PATH" KioskClient.sln /p:Configuration=Release
        shell: pwsh

      - name: Run Tests
        run: |
          choco install nuget.commandline --yes
          $testDlls = Get-ChildItem -Path test -Recurse -Filter *.dll | Where-Object { $_.Name -notmatch 'TestAdapter' }
          foreach ($dll in $testDlls) {
            Write-Host "Running tests in $($dll.FullName)"
            dotnet vstest $dll.FullName
          }
        shell: pwsh
